const SOUNDS = [
            {name: "MODPULSERAY_01m--Cartoon Insect.mp3"}, 
			{name: "45 CMPT DataTran Crix Sweetener SUP01_45.02.mp3"},
			{name:"Att Electronic Phone Ring.M for cicada.mp3"},
			{name:"bwire Steady Printer For Barb Wire Hybrid Insect_BWBEEP.M.mp3"},
			{name:"CA Crix Beeper From 6010-20-2_6BE.M.mp3"},
			{name:"Comedy, Bubble-DulComedy-Bing-High_BIRD_CYBIN.mp3"},
			{name:"Comedy, Rattle - Bubbly R.M Insect.mp3"},
			{name:"Comedy, Rattle - Space RatchetM Cicada.mp3"},
			{name:"Comedy, Rattle - Space__1.M Raspy Cicada.mp3"},
			{name:"Comedy, Rattle - Space__2Cicada.M.mp3"},
			{name:"Comedy, Rattle - Space__3.M Higher Bird Cicada.mp3"},
			{name:"Comedy, Warble - Saw - Bugs Swarm Rain Forest.mp3"},
			{name:"Computer Signature Beep For Parrot Speaks.mp3"},
			{name:"Critters 4 Card-reader El.M.mp3"},
			{name:"David Farmer Bug Zapper_da.mp3"},
			{name:"E2 Interesting Sh Telemet.M.mp3"},
			{name:"Electronic Baby Spider Ch.M.mp3"},
			{name: "Electronic Baby Spider__1.M.mp3"}, 
			{name: "Electronic Cartoon Fx For.M.mp3"},
			{name:"Electronic Fx For dream House.mp3"},
			{name:"Electronic Telemtry Beep -- Amusement Park Bird.mp3"},
			{name:"Electronic Tone_KOLRTON2.M.mp3"},
			{name:"Extracted From Other Comb.M.mp3"},
			{name:"Four Complex Beeps_4BEEPS.M.mp3"},
			{name:"Graphics Appear For Max B.M.mp3"},
			{name:"H3000 Upward Warble_HUPWB01.mp3"},
			{name:"H3000 Warble_HWARB01.mp3"},
			{name:"Hong Kong Fire Dept Sos B.M - Chattering Birds Loop.mp3"},
			{name:"Hovering, Glowing Tone__1.M.mp3"},
			{name:"Loop Of Electronic'focus'.M.mp3"},
			{name:"Looping Sound File_A-136.mp3"},

//should be thirty entries up above; need at least a hundred


			// {name: "_MODPULSERAY_01.M -- Cartoon Insect.mp3"}, 
			{name: "45 CMPT DataTran Crix Sweetener SUP01_45.02.mp3"},
			{name:"Att Electronic Phone Ring.M for cicada.mp3"},
			{name:"bwire Steady Printer For Barb Wire Hybrid Insect_BWBEEP.M.mp3"},
			{name:"CA Crix Beeper From 6010-20-2_6BE.M.mp3"},
			{name:"Comedy, Bubble - DulComedy, Bing - High_BIRD_CYBIN.M.mp3"},
			{name:"Comedy, Rattle - Bubbly R.M Insect.mp3"},
			{name:"Comedy, Rattle - Space RatchetM Cicada.mp3"},
			{name:"Comedy, Rattle - Space__1.M Raspy Cicada.mp3"},
			{name:"Comedy, Rattle - Space__2Cicada.M.mp3"},
			{name:"Comedy, Rattle - Space__3.M Higher Bird Cicada.mp3"},
			{name:"Comedy, Warble - Saw - Bugs Swarm Rain Forest.mp3"},
			{name:"Computer Signature Beep For Parrot Speaks.mp3"},
			{name:"Critters 4 Card-reader El.M.mp3"},
			{name:"David Farmer Bug Zapper_da.mp3"},
			{name:"E2 Interesting Sh Telemet.M.mp3"},
			{name:"Electronic Baby Spider Ch.M.mp3"},
			{name: "Electronic Baby Spider__1.M.mp3"}, 
			{name: "Electronic Cartoon Fx For.M.mp3"},
			{name:"Electronic Fx For 'dream House'.mp3"},
			{name:"Electronic Telemtry Beep -- Amusement Park Bird.mp3"},
			{name:"Electronic Tone_KOLRTON2.M.mp3"},
			{name:"Extracted From Other Comb.M.mp3"},
			{name:"Four Complex Beeps_4BEEPS.M.mp3"},
			{name:"Graphics Appear For Max B.M.mp3"},
			{name:"H3000 Upward Warble_HUPWB01.mp3"},
			{name:"H3000 Warble_HWARB01.mp3"},
			{name:"Hong Kong Fire Dept Sos B.M - Chattering Birds Loop.mp3"},
			{name:"Hovering, Glowing Tone__1.M.mp3"},
			{name:"Loop Of Electronic'focus'.M.mp3"},
			{name:"Looping Sound File_A-136.mp3"},
]